### ISSUE TITLE
Default ports

### ISSUE THREAD

**Issue by alexseys** [samdoran/ansible-role-firewall#1]
Hi, 
Seems you have default ports defined in defaluts/main.yml
Say i dont need udp 161 opened and I do not need any udp ports open.
when i try to remove port # from defaluts/main.yml error:
failed: [server] (item=None) => {"changed": false, "item": null, "msg": "ERROR: Exception caught: org.fedoraproject.FirewallD1.Exception: INVALID_PORT: '' is invalid port range Permanent operation"}

when i try to remove whole section from defaluts/main.yml or remove file entirely:
firewall_allowed_udp_ports:
  - 0
error:
fatal: [server]: FAILED! => {"msg": "'firewall_allowed_udp_ports' is undefined"}

My playbook looks like this:

```yaml
---
- hosts: all
  roles:
    - role: firewalld
      firewall_strict: yes
      firewall_allowed_tcp_ports:
        - 4903
        - 7802
        - 7788
        - 4889
        - 4323
```

How would i go about not adding default ports or process default.yml?

Thank you
Al
